# Generated by Django 4.0.5 on 2022-06-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_userbankaccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
